export const ARTIST_NAMES = [
    "KXNG VEX", "RYLO KANE", "LUCIFER JAY", "DARKO", "ZAYVEN", 
    "PHANTOM X", "KINETIC", "SHADE", "KROWN KOLLECTIVE", "VODKA",
    "GHOST", "BLITZ", "REAPER", "ONYX", "STORM", "VENOM"
];

export const VIBES = [
    "RAW SOUND", "REAL STORIES", "NO LIMITS", "UNDERGROUND", 
    "UNAPOLOGETIC", "DEVIL INSIDE", "BUILT DIFFERENT", "NO RULES"
];
